image:
  registry: docker.io
  repository: bitnami/ghost
  tag: 3.35.5-debian-10-r0

# ghostProtocol: http
# ghostHost: evelyn-mario.wedding
# ghostPort:
ghostPath: /

ghostUsername: chase
ghostEmail: chase@sillevis.net
ghostBlogTitle: "evelyn X mario"
allowEmptyPassword: true
existingSecret:
  name: custom-ghost
  keyMapping:
    ghost-password: ghost-password
#   smtp-password: mySmtpPasswordKey

mariadb:
  ## Whether to deploy a mariadb server to satisfy the applications database requirements. To use an external database set this to false and configure the externalDatabase parameters
  enabled: true
  ## Disable MariaDB replication
  replication:
    enabled: false

  master:
    persistence:
      enabled: true
      storageClass: do-block-storage
      accessMode: ReadWriteOnce
      size: 8Gi

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

resources:
  requests:
    memory: 128Mi
    cpu: 300m

service:
  type: ClusterIP

  ## HTTP Port
  port: 80

persistence:
  enabled: true
  storageClass: do-block-storage
  accessMode: ReadWriteOnce
  size: 8Gi
  path: /bitnami


ingress:
  enabled: true
  certManager: true

  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"

  hosts:
    - name: evelyn-mario.wedding
      path: /
      tls: true

      tlsHosts:
        - www.evelyn-mario.wedding
        - evelyn-mario.wedding

      tlsSecret: evelyn-mario.wedding-tls
