apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quakejs
  namespace: quakejs
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: quake.sillevis.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quake
                port:
                  name: client
  tls:
    - hosts:
        - quake.sillevis.net
      secretName: quake-sillevis-net-tls
