apiVersion: v1
kind: Service
metadata:
  name: quakejs
  namespace: quakejs
  labels:
    run: quakejs
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    run: quakejs
