apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/name: ghost
    app.kubernetes.io/component: ghost
    app.kubernetes.io/instance: zgranitowego
  name: ghost-debug
  namespace: zgranitowegowzgorza
spec:
  securityContext:
    runAsUser: 999
  containers:
  - env:
    - name: BITNAMI_DEBUG                                                                                                                                            
      value: "true"
    - name: ALLOW_EMPTY_PASSWORD                                                                                                                                     
      value: "yes"                                                                                                                                                   
    - name: GHOST_DATABASE_HOST                                                                                                                                      
      value: private-db-mysql-ams3-86213-do-user-2623710-0.b.db.ondigitalocean.com                                                                                   
    - name: GHOST_DATABASE_PORT_NUMBER                                                                                                                               
      value: "25060"                                                                                                                                                 
    - name: GHOST_DATABASE_NAME                                                                                                                                      
      value: zgranitowego
    - name: GHOST_DATABASE_USER
      value: zgranitowego                                                                                                                                            
    - name: GHOST_DATABASE_PASSWORD                                                                                                                                  
      valueFrom:                                                                                                                                                     
        secretKeyRef:                                                                                                                                                
          key: mysql-password                                                                                                                                        
          name: mysql-password                                                                                                                                       
    - name: GHOST_DATABASE_ENABLE_SSL                                                                                                                                
      value: "true"
    - name: MYSQL_CLIENT_ENABLE_SSL                                                                                                                                  
      value: "yes"                                                                                                                                                   
    - name: GHOST_DATABASE_SSL_CA_FILE                                                                                                                               
      value: /secrets/mysql-ca-certificates.crt                                                                                                                      
    - name: GHOST_HOST                                                                                                                                               
      value: wolfdogs.pl/                                                                                                                                   
    - name: GHOST_PORT_NUMBER                                                                                                                                        
      value: "2368"
    - name: GHOST_USERNAME                                                                                                                                           
      value: chase                                                                                                                                                   
    - name: GHOST_PASSWORD                                                                                                                                           
      valueFrom:                                                                                                                                                     
        secretKeyRef:                                                                                                                                                
          key: ghost-password                                                     
          name: custom-ghost
    - name: GHOST_EMAIL
      value: chase@sillevis.net
    - name: BLOG_TITLE
      value: Wolfdogs
    - name: GHOST_ENABLE_HTTPS                                                                                                                                       
      value: "no"
    - name: GHOST_EXTERNAL_HTTP_PORT_NUMBER                                                                                                                          
      value: "80"                                                                                                                                                    
    - name: GHOST_EXTERNAL_HTTPS_PORT_NUMBER
      value: "443"                       
    - name: GHOST_SKIP_BOOTSTRAP                                                  
      value: "no"                        
    - name: LOG_LEVEL                                                             
      value: DEBUG
    image: docker.io/bitnami/ghost:5.33.6-debian-11-r0
    imagePullPolicy: IfNotPresent
    name: ghost
    command:
    - bash
    args:
    - -c
    - "sleep 36000"
    ports:
    - containerPort: 2368
      name: http
      protocol: TCP
    resources:
      requests:
        cpu: 10m
        memory: 30Mi
    volumeMounts:
    - mountPath: /bitnami/ghost
      name: ghost-data
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-58t5q
      readOnly: true
  volumes:
  - name: ghost-data
    persistentVolumeClaim:
      claimName: ghost
  - name: default-token-58t5q
    secret:
      defaultMode: 420
      secretName: default-token-58t5q