image:
  registry: docker.io
  repository: bitnami/ghost
  tag: 3.35.5-debian-10-r1
  #tag: 2.37.0-r11

ghostProtocol: https
ghostHost: wolfdogs.pl
ghostPort: 443
ghostPath: /

ghostUsername: chase
ghostEmail: chase@wolfdogs.pl
ghostBlogTitle: "Z Granitowego Wzgórza"
allowEmptyPassword: true
existingSecret:
  name: custom-ghost
  keyMapping:
    ghost-password: ghost-password
#   smtp-password: mySmtpPasswordKey

mariadb:
  ## Whether to deploy a mariadb server to satisfy the applications database requirements. To use an external database set this to false and configure the externalDatabase parameters
  enabled: true
  ## Disable MariaDB replication
  replication:
    enabled: false

  master:
    persistence:
      enabled: true
      storageClass: do-block-storage
      accessMode: ReadWriteOnce
      size: 8Gi

resources:
  requests:
    memory: 175Mi
    cpu: 100m
  limits:
    memory: 500Mi
    cpu: 500m
service:
  type: ClusterIP

  ## HTTP Port
  port: 80

persistence:
  enabled: true
  storageClass: do-block-storage
  accessMode: ReadWriteOnce
  size: 8Gi
  path: /bitnami


ingress:
  enabled: true
  certManager: true

  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.org/client-max-body-size: "10m"

  hosts:
    - name: www.wolfdogs.pl
      path: /
      tls: true

      tlsHosts:
        - www.wolfdogs.pl
        - wolfdogs.pl

      tlsSecret: wolfdogs.pl-tls
    - name: wolfdogs.pl
      path: /
      tls: true

      tlsHosts:
        - www.wolfdogs.pl
        - wolfdogs.pl

      tlsSecret: wolfdogs.pl-tls
