ghostProtocol: https
ghostHost: wolfdogs.pl
ghostPort: 443
ghostPath: /

#image:
#  debug: true

ghostUsername: chase
ghostEmail: chase@wolfdogs.pl
ghostBlogTitle: "Z Granitowego Wzgórza"
allowEmptyPassword: false
existingSecret: custom-ghost

updateStrategy:
  type: Recreate

livenessProbe:
  enabled: false
readinessProbe:
  enabled: false

mysql:
  enabled: false
mariadb:
  enabled: false

#ghostSkipInstall: true
#extraEnvVars:
#  - name: GHOST_SKIP_BOOTSTRAP
#    value: "yes"

externalDatabase:
  host: private-db-mysql-ams3-86213-do-user-2623710-0.b.db.ondigitalocean.com
  port: 25060
  user: zgranitowego
  database: zgranitowego
  existingSecret: mysql-password
  ssl: true
  sslCaFile: /secrets/mysql-ca-certificates.crt

extraVolumeMounts:
  - name: mysql-ca
    mountPath: /secrets/mysql-ca-certificates.crt
    subPath: mysql-ca-certificates.crt
    readOnly: true
extraVolumes:
  - name: mysql-ca
    secret:
      secretName: mysql-ca-bundle
      optional: false

resources:
  requests:
    memory: 175Mi
    cpu: 100m
  limits:
    memory: 250Mi
    cpu: 500m

service:
  type: ClusterIP

  ## HTTP Port
  port: 80

persistence:
  enabled: true
  storageClass: do-block-storage
  accessMode: ReadWriteOnce
  size: 8Gi
  path: /bitnami
  existingClaim: ghost

ingress:
  enabled: true
  certManager: true

  hostname: wolfdogs.pl
  path: /
  tls: true
  ingressClassName: "nginx"

  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
