apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitlbee
  namespace: sillevis
  labels:
    app: bitlbee
spec:
  template:
  selector:
    matchLabels:
      app: bitlbee
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0%
  template:
    metadata:
      labels:
        app: bitlbee
    spec:
      containers:
      - name: bitlbee
        image: deviavir/docker-bitlbee
        imagePullPolicy: "Always"
        ports:
        - name: bitlbee
          containerPort: 6667
        volumeMounts:
          - name: conf
            mountPath: /etc/bitlbee/bitlbee.conf
            subPath: bitlbee.conf
          - name: data
            mountPath: /var/lib/bitlbee
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: bitlbee-data
        - name: conf
          secret:
            secretName: bitlbee-conf
            items:
              - key: conf
                path: bitlbee.conf
