apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitlbee-data
  namespace: sillevis
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
