apiVersion: v1
kind: Service
metadata:
  name: bitlbee
  namespace: sillevis
  labels:
    app: bitlbee
spec:
  type: ClusterIP
  ports:
  - name: bitlbee
    port: 6667
    targetPort: 6667
  selector:
    app: bitlbee
