controller:
  replicaCount: 1
  publishService:
    enabled: true
  config:
    use-forward-headers: true
    compute-full-forward-for: true
    proxy-body-size: "10240m"
  service:
    externalTrafficPolicy: "Local"
