apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: lordofthecode
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  rules:
  - host: lordofthecode.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 80
  - host: www.lordofthecode.nl
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 80
  tls:
  - hosts:
    - lordofthecode.nl
    - www.lordofthecode.nl
    secretName: lord-of-the-code-tls
