apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-files
  namespace: lordofthecode
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
